### ISSUE TITLE
Error when using license URL

### ISSUE THREAD

**Issue by mquekel** [akuryan/vsts.extensions#2]
Hi Anton,

Good idea to make an extension for deploying Sitecore.
I am trying to use this extension for deploying the infrastructure.
I am using the ARM Templates for Sitecore 9.0.2
https://github.com/Sitecore/Sitecore-Azure-Quickstart-Templates/tree/master/Sitecore%209.0.2/XPSingle

In my build definition I filled in all the parameters in the azuredeploy.parameters.json but I get the following errors.
##[error]Cannot process command because of one or more missing mandatory parameters: sitecoreAdminPassword licenseXml sqlServerLogin sqlServerPassword singleMsDeployPackageUrl xcSingleMsDeployPackageUrl.

Do you have any idea why I get this error?

Kind regards,
Martijn

**Comment by akuryan** [comment]
As you see, all those parameters have to be specified in parameters file: https://github.com/Sitecore/Sitecore-Azure-Quickstart-Templates/blob/master/Sitecore%209.0.2/XPSingle/azuredeploy.parameters.json
Can you check your parameters file - do it have those parameters specified? And can you check if you specified correct path in 'ARM parameters path' field?

**Comment by mquekel** [comment]
I checked the Path and see that all the parameters in the file are specified.
In your blog I see that you are referring to the ARM templates from Rob Habraken.
I am using the ARM templates from Sitecore. Are these templates also supported by your extension?

**Comment by akuryan** [comment]
Yes, default parameters are supported.
You can specify ```system.debug = True``` in Release/Build variables to check verbose output of an extension. It shall list all parameters (seek log for string ```Listing keys AFTER filling up by extension:```).

**Comment by mquekel** [comment]
I used the system.debug = True and this helped me to get one step further.
After changing the format of the azuredeploy.parameters.json file. the variables are now loaded. I can see this in the log files.
However I do get another error:
'The template resource 'templateLinkBase' at line '28' and column '29' is not valid'

This is probably because the ARM Templates supplied by Sitecore are using a variable templateLink that expects a URL to a location where the Templates are uploaded. 

This is also mentioned in an article from Jan Bluemink http://sitecore.stockpick.nl/english/sitecore-azure-arm/

**Comment by akuryan** [comment]
Ahhh, I see... I fixed this issue with following approach:

- Added one more task to my release: ```Azure File Copy``` before Sitecore deployer to upload templates to Azure Storage container. This task will upload templates to Azure Storage container in blob folder, which I defined in variable ```$(blobPrefix)``` (```blobPrefix``` is equal to ```$(Release.ReleaseId)/$(Release.EnvironmentName)``` which allows me to have separate templates for separate environments and releases). Task will output SAS and Storage container URI in variables ```storageUri``` and ```storageSas```
![1](https://user-images.githubusercontent.com/1794306/42159309-fb8a288e-7dfb-11e8-9e69-ce298ef238db.png)

- In Sitecore Deploy task in field ```Additional ARM parameters``` I am defining following string ```templateLinkBase=$(storageUri)/$(blobPrefix)/ \n templateLinkAccessToken=$(storageSas)```
This allows me to inject URL for storage account and it's SAS, so, template starts deploying from local disk, but will get nested templates from Azure Storage account (actually, this is ARM limitation: you could not use nested templates from local disk - they shall be always located on URI, **accessible to host, which is executing script**, _hence, this upload to Azure Storage task addition_)

Actually, if you are not modifying nested templates (mine modifications included HTTP/2, TLS 1.2 and some other stuff, required for our application work) - you can change templateLinkBase variable to GitHub URL, pointing it to Sitecore Azure QuickStart templates

**Comment by mquekel** [comment]
Thanks! this solution is working for me.
I think it would be a great improvement to add an option to upload the template files to a storage account, This will be helpful for supporting Sitecore 9 templates as well. But for now the workaround with the Additional Parameters field will work.

**Comment by akuryan** [comment]
Thank you for idea, I will look into it.
For now, I will add an explanation how to use linked templates in extension overview
